### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by zorbash** [kittoframework/kitto#5]
A Kitto dashboard should require minimal or no changes to be deployed to Heroku.

Instructions featuring the steps required to be up and running on Heroku must be added in the [wiki](https://github.com/kittoframework/kitto/wiki).

The demo and the scaffolded dashboard may then have a 
![selection_054](https://cloud.githubusercontent.com/assets/645514/20109673/d2e4de4c-a5e9-11e6-87a0-d72dd0f42607.png) 
button in the README.

Installer Required Changes

- [x] Add a sample Procfile (02280fa7d)
- [x] Add a sample elixir_buildpack.config (1294cf9c)
- [x] Add heroku-postbuild action to build assets
- [x] Add wiki page

**Comment by zorbash** [comment]
Some work in progress can be found in https://github.com/kittoframework/demo/commits/heroku
which is succesfully deployed at: http://kitto.herokuapp.com

**Comment by zorbash** [comment]
An actual heroku button in the readme is not really required since one would want to tweak even a little a template dashboard before deploying it.

**Comment by davejlong** [comment]
Can we add it to the dashboard template that’s created when someone runs
`mix kitto.new`?

On November 17, 2016 at 2:53:55 PM, Dimitrios Zorbas (
notifications@github.com) wrote:

An actual heroku button in the readme is not really required since one
would want to tweak even a little a template dashboard before deploying it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/kittoframework/kitto/issues/5#issuecomment-261351211,
or mute the thread

**Comment by zorbash** [comment]
We can add Heroku deployment instructions in the generated README or at least a link to the wiki page.
But not the deploy button. It only mostly makes sense for open-source projects like [rauchg/slackin](https://github.com/rauchg/slackin). We can add it to kittoframework/demo though, for someone who wishes to evaluate Kitto Heroku deployment.
